import type { Category, Product } from '@/types/product';
import type { User } from '@/types/user';

const now = () => new Date().toISOString();

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-electronics', name: 'Eletrônicos', slug: 'eletronicos' },
  { id: 'cat-home', name: 'Casa', slug: 'casa' },
  { id: 'cat-books', name: 'Livros', slug: 'livros' },
  { id: 'cat-fashion', name: 'Moda', slug: 'moda' },
  { id: 'cat-grocery', name: 'Mercado', slug: 'mercado' },
  { id: 'cat-games', name: 'Games', slug: 'games' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    name: 'Smartphone Galaxy',
    description: 'Smartphone Android com tela AMOLED 6.5", 128GB, câmera tripla 50MP.',
    categoryId: 'cat-electronics',
    price: 2499.9,
    imageUrl: 'https://images.unsplash.com/photo-1505468726633-0069fc52f4b9?auto=format&fit=crop&w=600&q=80',
    availableQuantity: 25,
    active: true,
    createdAt: now(),
  },
  {
    id: 'prod-02',
    name: 'Notebook Pro',
    description: 'Notebook 14" Intel i7, 16GB RAM, SSD 512GB, Windows 11.',
    categoryId: 'cat-electronics',
    price: 5899.0,
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=600&q=80',
    availableQuantity: 10,
    active: true,
    createdAt: now(),
  },
  {
    id: 'prod-03',
    name: 'Headset Bluetooth',
    description: 'Fone over-ear sem fio com cancelamento de ruído ativo, 30h bateria.',
    categoryId: 'cat-electronics',
    price: 449.9,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    availableQuantity: 40,
    active: true,
    createdAt: now(),
  },
  {
    id: 'prod-04',
    name: 'Mouse Gamer',
    description: 'Mouse RGB 16000 DPI, 7 botões programáveis, sensor óptico.',
    categoryId: 'cat-games',
    price: 199.9,
    imageUrl: 'https://images.unsplash.com/photo-1623820919239-0d0ff10797a1?auto=format&fit=crop&w=600&q=80',
    availableQuantity: 60,
    active: true,
    createdAt: now(),
  },
  {
    id: 'prod-05',
    name: 'Teclado Mecânico',
    description: 'Teclado mecânico ABNT2 com switches azuis e RGB por tecla.',
    categoryId: 'cat-games',
    price: 379.9,
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
    availableQuantity: 30,
    active: true,
    createdAt: now(),
  },
  {
    id: 'prod-06',
    name: 'Livro Java 21',
    description: 'Guia completo de Java 21 com Spring Boot 3 e arquitetura limpa.',
    categoryId: 'cat-books',
    price: 129.9,
    imageUrl: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80',
    availableQuantity: 80,
    active: true,
    createdAt: now(),
  },
  {
    id: 'prod-07',
    name: 'Smart TV 50"',
    description: 'Smart TV 4K UHD 50", HDR10+, Wi-Fi 6, 3 HDMI, Google TV.',
    categoryId: 'cat-electronics',
    price: 2899.0,
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=600&q=80',
    availableQuantity: 8,
    active: true,
    createdAt: now(),
  },
  {
    id: 'prod-08',
    name: 'Cafeteira Elétrica',
    description: 'Cafeteira programável 1.5L, 12 xícaras, com timer e jarra térmica.',
    categoryId: 'cat-home',
    price: 349.0,
    imageUrl: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=600&q=80',
    availableQuantity: 20,
    active: true,
    createdAt: now(),
  },
  {
    id: 'prod-09',
    name: 'Cadeira de Escritório',
    description: 'Cadeira ergonômica com apoio lombar ajustável e braços 4D.',
    categoryId: 'cat-home',
    price: 1299.0,
    imageUrl: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&w=600&q=80',
    availableQuantity: 4,
    active: true,
    createdAt: now(),
  },
  {
    id: 'prod-10',
    name: 'Camiseta Básica',
    description: 'Camiseta de algodão pima, gola careca, várias cores.',
    categoryId: 'cat-fashion',
    price: 79.9,
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80',
    availableQuantity: 100,
    active: true,
    createdAt: now(),
  },
  {
    id: 'prod-11',
    name: 'Console GameBox',
    description: 'Console next-gen com SSD 1TB, controle wireless e 2 jogos inclusos.',
    categoryId: 'cat-games',
    price: 4299.0,
    imageUrl: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=600&q=80',
    availableQuantity: 0,
    active: true,
    createdAt: now(),
  },
  {
    id: 'prod-12',
    name: 'Mochila Executiva',
    description: 'Mochila para notebook 15.6" com porta USB e compartimento térmico.',
    categoryId: 'cat-fashion',
    price: 249.9,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
    availableQuantity: 35,
    active: true,
    createdAt: now(),
  },
];

export interface MockUser extends User {
  password: string;
}

export const MOCK_USERS: MockUser[] = [
  {
    id: 'user-client',
    name: 'Cliente Demo',
    email: 'cliente@shopbank.com',
    cpf: '52998224725',
    role: 'CLIENT',
    password: '123456',
    createdAt: now(),
  },
  {
    id: 'user-admin',
    name: 'Admin Demo',
    email: 'admin@shopbank.com',
    role: 'ADMIN',
    password: '123456',
    createdAt: now(),
  },
];
