spring.application.name=shopbank

spring.datasource.url=jdbc:h2:mem:shopbank
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

server.port=8080

springdoc.swagger-ui.path=/swagger-ui.html

shopbank.marketplace.fee-rate=${SHOPBANK_MARKETPLACE_FEE_RATE:0.00}

abacatepay.api-key=${ABACATEPAY_API_KEY:}
abacatepay.webhook-secret=${ABACATEPAY_WEBHOOK_SECRET:}
abacatepay.webhook-signature-key=${ABACATEPAY_WEBHOOK_SIGNATURE_KEY:t9dXRhHHo3yDEj5pVDYz0frf7q6bMKyMRmxxCPIPp3RCplBfXRxqlC6ZpiWmOqj4L63qEaeUOtrCI8P0VMUgo6iIga2ri9ogaHFs0WIIywSMg0q7RmBfybe1E5XJcfC4IW3alNqym0tXoAKkzvfEjZxV6bE0oG2zJrNNYmUCKZyV0KZ3JS8Votf9EAWWYdiDkMkpbMdPggfh1EqHlVkMiTady6jOR3hyzGEHrIz2Ret0xHKMbiqkr9HS1JhNHDX9}
abacatepay.webhook-signature-validation-enabled=${ABACATEPAY_WEBHOOK_SIGNATURE_VALIDATION_ENABLED:true}
abacatepay.webhook-auto-registration-enabled=${ABACATEPAY_WEBHOOK_AUTO_REGISTRATION_ENABLED:true}
abacatepay.webhook-name=${ABACATEPAY_WEBHOOK_NAME:ShopBank Payments}
abacatepay.sandbox=${ABACATEPAY_SANDBOX:true}
abacatepay.api-base-url=${ABACATEPAY_API_BASE_URL:https://api.abacatepay.com/v2}
abacatepay.public-url=${APP_PUBLIC_URL:http://localhost:8080}
abacatepay.return-url=${FRONTEND_PENDING_URL:http://localhost:4200/payment/pending}
abacatepay.completion-url=${FRONTEND_SUCCESS_URL:http://localhost:4200/payment/success}
abacatepay.failure-url=${FRONTEND_FAILURE_URL:http://localhost:4200/payment/failure}
abacatepay.pix-expires-in=${ABACATEPAY_PIX_EXPIRES_IN:3600}
abacatepay.checkout-max-installments=${ABACATEPAY_CHECKOUT_MAX_INSTALLMENTS:12}

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.jms.pub-sub-domain=false
